on:
  push:
    branches: [master]
jobs:
  check-code-conformity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
      - name: Install PHP Code Sniffer
        run: composer global require "squizlabs/php_codesniffer=*"
      - name: Check code conformity
        run: phpcs --standard=PSR2 Validateur.php